name: Word Statistic

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Run Statistic
        run: |
          python3 test/process.py

      - name: Test
        run: python3 test/test.py
